Feat: Create Refuel page + Make Nav Functional
Extent-Org/Extent-Frontend pull request #20
Opened 2022-12-24 16:37 UTC by Vijay-K-2003

![Screenshot from 2022-12-24 22-05-49](https://user-images.githubusercontent.com/75903092/209444375-fbf784d6-56aa-4ff1-9211-ac4691e2838a.png)
![Screenshot from 2022-12-24 22-06-45](https://user-images.githubusercontent.com/75903092/209444407-49629310-d044-471c-9bfc-f964bb3b49a5.png)

2022-12-25 06:05 UTC, nlok5923 requested changes

2022-12-25 06:05 UTC, nlok5923 commented on src/components/RefuelPage/RefuelPage.tsx
> +                        <input type="text" name="daitoken" id="daitoken" placeholder='Enter amount of Tokens' />
type here should be number also it must be a required field.

2022-12-25 06:05 UTC, nlok5923 commented on src/components/RefuelPage/RefuelPage.tsx
> +                        <input type="text" name="daitoken" id="daitoken" placeholder='Enter amount of Tokens' />
Also specify a min limit of 0.0001 for now

2022-12-26 12:58 UTC, darshanhande11 approved these changes

2022-12-26 13:37 UTC, solankidivyam approved these changes

2022-12-27 16:30 UTC, nlok5923 approved these changes

2022-12-27 16:32 UTC, merged