Feat: FAQ Page
Extent-Org/Extent-Frontend pull request #22
Opened 2022-12-28 09:55 UTC by Vijay-K-2003

![Screenshot from 2022-12-28 15-24-10](https://user-images.githubusercontent.com/75903092/209793643-0eb4a99c-eb95-4a19-8de3-fbcbeaecc850.png)
![Screenshot from 2022-12-28 15-24-29](https://user-images.githubusercontent.com/75903092/209793718-a1465806-f9bb-461d-b677-5385f955512e.png)
![Screenshot from 2022-12-28 15-25-34](https://user-images.githubusercontent.com/75903092/209793837-8e02cd3b-ee34-46c3-8bd4-f507d6658053.png)

2022-12-29 08:17 UTC, darshanhande11 requested changes
@Vijay-K-2003 Add some animation to the accordions when they open. You can use [this](https://www.w3schools.com/howto/howto_js_accordion.asp) for reference.

2022-12-30 04:58 UTC, nlok5923 commented
@Vijay-K-2003 
Some changes needed

- The animation still is quite abrupt make it smoother.
- Use symbol + and - for collapsing and expanding in proportionate size. for now the - sign is too small.
- Change FAQs -> FAQ's

2022-12-30 09:00 UTC, Vijay-K-2003 commented
Ok

2022-12-30 16:04 UTC, darshanhande11 requested changes
@Vijay-K-2003 Please fix the following:

The Nav is transparent while scrolling, make it's behaviour like that on the Product Page.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/56157418/210089510-5f6b4164-76d8-47f3-802e-b277fe5dc2b4.png">

2022-12-30 16:07 UTC, nlok5923 commented
Adding to it please choose a uniform animation style as per the current behaviour the accordion animation getting slower on expanding which is looking little weird.

2022-12-30 16:12 UTC, darshanhande11 commented
@Vijay-K-2003 

> Adding to it please choose a uniform animation style as per the current behaviour the accordion animation getting slower on expanding which is looking little weird.

Animations should look like [this](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_accordion_symbol). Even though you can use framer-motion but please make sure that you achieve this effect else you can take reference from w3schools.

2022-12-30 17:00 UTC, darshanhande11 requested changes
@Vijay-K-2003 It's alright while opening but when clicked for closing the accordion there is more delay. While closing the accordion the delay should be equal to the delay while opening. Please compare the w3 schools accordion reference with the localhost.

2022-12-30 17:00 UTC, darshanhande11 commented on src/components/FAQPage/Accordion/Accordion.tsx
> +        <div className="accordion">
Make the complete accordion div clickable and not just the accordion__question and accordion__answer.

2022-12-30 17:18 UTC, Vijay-K-2003 commented
I have tried to reduce the calculative delay by reducing max height to 50vh AND made complete accordion clickable.

2022-12-30 17:46 UTC, darshanhande11 requested changes
@Vijay-K-2003 It almost looks good and like the design. Just don't give the answer a max-height. Also, one more change:

Make the + icon proportionate to - icon. Like while opening accordion the horizontal line of the + icon should stay as it is and the vertical line should disappear and vice versa while closing.

2022-12-30 17:46 UTC, darshanhande11 commented on src/components/FAQPage/Accordion/Accordion.scss
> +                max-height: 50vh;
Giving a pre-defined height to the answer wrap div would cause overflow at some point when the content is more than the given height. Why are you giving max-height to the answer-wrap? Let the content inside it determine it's height.

2022-12-30 17:48 UTC, Vijay-K-2003 commented
+ and - are from font so should I change it to icon

2022-12-30 17:50 UTC, Vijay-K-2003 commented
Max height is required for animation

2022-12-30 17:55 UTC, darshanhande11 commented
> * and - are from font so should I change it to icon

Yes, use icons which can be resized with font-size properties. You can use [React Icons](https://react-icons.github.io/react-icons/search) package which is already installed in this project.

2022-12-30 18:07 UTC, darshanhande11 commented
> Max height is required for animation

Well, now that you have set the max-height to 50vh, but what if the content requires a height > 50vh, then the content overflows and the remaining content isn't visible. So, for now add overflow-y: auto so that it's scrollable for this case where it is breaking currently.

2022-12-31 04:26 UTC, nlok5923 commented
Changes needed:
- Can you please add some animation (kindoff like rotation) in translation '+' -> '-'.
- Both FAQ page and refuel page should have the footer with them.

2022-12-31 06:41 UTC, darshanhande11 approved these changes

2022-12-31 06:43 UTC, nlok5923 approved these changes

2022-12-31 07:05 UTC, merged